sudo: false
language: ruby
rvm:
  - 2.5.5
services:
  - postgresql
before_install:
  - gem install bundler:1.17.2
before_script:
  - cd spec/dummy
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../../
